seed: 42
resume_from_checkpoint: latest
pretrained_model_name_or_path: /content/gdrive/MyDrive/Train_SD15_Inpaint/PowerPaint/checkpoints/sd15-inpainting/stable-diffusion-inpainting
output_dir: /content/gdrive/MyDrive/Train_SD15_Inpaint/output_models
resolution: 512
train_batch_size: 10
gradient_accumulation_steps: 2
num_train_epochs: 25
learning_rate: 1e-5
mixed_precision: fp16
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
checkpointing_steps: 5000
validation_steps: 5000
checkpoints_total_limit: 5
max_train_samples: null
use_8bit_adam: true
allow_tf32: true
dataloader_num_workers: 4
train_data:
  datasets:
  - dataset_class: COCODataset
    data_root: /content/coco_full_clean/train
    prob: 1.0
